metricbeat.config.modules:
  path: /usr/share/metricbeat/modules.d/*.yml
  reload.enabled: true

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']

setup.kibana:
  host: "kibana:5601"

#metricbeat.modules:
#- module: docker
#    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
#    hosts: ["unix:///var/run/docker.sock"]
#    period: 10s
