version: '2.2'

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  dbdata:

services:
  db:
    image: postgres:9.6
    volumes:
     - dbdata:/var/lib/postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar
      POSTGRES_PASSWORD: sonar

  sonarqube:
    image: sonarqube:alpine
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
     - default
     - gateway_default
    labels:
      - com.ansible.role=sonarqube
      - "traefik.frontend.rule=Host:sonarcluster.local;PathPrefix:/"
      - "traefik.port=9000"
      - "traefik.enabled=true"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

networks:
  default:
    external: false
  gateway_default:
    external: true

